project:
  type: website
  output-dir: .

website:
  title: "Søren Damsbo-Svendsen"
  search: false
  page-footer: | 
    This website is powered by [![](https://quarto.org/quarto.png){height=15}](https://quarto.org/) and <a href="https://pages.github.com" style="text-decoration: none">{{< fa brands github >}} GitHub Pages</a>.
  navbar:
    right:
      - text: "Home"
        file: index.qmd
      - research.qmd
  #     - blog.qmd
  #     - icon: github
  #       href: https://github.com/
  #     - icon: twitter
  #       href: https://twitter.com

format:
  html:
    theme: ./theme.scss

 

