project:
  type: website

website:
  title: "Søren Damsbo-Svendsen"
  search: false
  navbar:
    right:
      - text: "Home"
        file: index.qmd
      - research.qmd
  #     - blog.qmd
  #     - icon: github
  #       href: https://github.com/
  #     - icon: twitter
  #       href: https://twitter.com

format:
  html:
    theme: theme.scss



