---
title: Research
---

## Published journal articles

#### __1. Ineffectiveness of priming and contextualizing personal weather experiences: Evidence from a survey experiment on summer heat__

*Published in Public Opinion Quarterly (2025), co-authored with Tobias Heide-Jørgensen* [_[link to article](https://academic.oup.com/poq/advance-article-abstract/doi/10.1093/poq/nfae067/8097947)_]

**Abstract:** We study whether communication that attributes extreme weather to climate change along with individuals’ personal weather experiences can mobilize increased support for climate change action and policies. Using a preregistered representative survey experiment from Denmark, we randomly assign respondents to two treatments: (a) a hot weather prime that asks them to recall the extreme Danish summer of 2018 and (b) contextualizing information that links extreme weather events to climate change. We find that priming past heat experience does not foster increased climate awareness, opinions, or willingness to act or pay. We also fail to find that climate communication strengthens the effect of heat experience on climate attitudes or matters on its own. We argue, and provide tentative evidence, that this is because people in northern regions often recall heat spells as something pleasant rather than perceiving them as a risk. Similar results were obtained using quasi-experimental data on recent local temperature deviations instead of past heat experiences. Overall, the results suggest that what is objectively and meteorologically extreme may subjectively invoke positive feelings and therefore not increase support for climate action. We discuss the implications for climate communication and opinion formation.

#### __2. Pro-climate voting in response to local flooding__

*Published in Political Behavior (2024)* [_[link to open access article](https://link.springer.com/article/10.1007/s11109-024-09984-0)_]

**Abstract:** Human-caused global warming exacerbates extreme weather events, but evidence of their impact on political behavior is limited. This article presents a twofold study of the effects of severe storm surge flooding on pro-climate voting in Danish elections. Using difference-in-differences research designs and administrative data, the article shows how the electoral effects of local flooding depends on the intensity of the experience. Voting for pro-climate parties in Danish national elections increased by around 2-3 percentage points in polling districts with flooding. Voting for local election candidates, who communicate a priority for climate issues and can have substantial influence on municipal climate policy, also increased four years after the flood, however only in districts with extreme flooding. Severe flooding increased the relative election chances of marginal pro-climate candidates by around five percentage points. Responsiveness to local flooding depends on the local extremity of the event and, possibly, local citizens' pre-existing climate awareness. The ostensibly modest effects are illustrative of electoral decision-making, even if the practical political and environmental implications are limited. By raising the salience of climate issues, personal flooding experience shapes voting behavior in a changing climate.

#### __3. Anxious but hesitant to act: The impact of concurrent priming of the climate crisis and the war in ukraine on public support__

*Published in International Journal of Public Opinion Research (2024), co-authored with Jakob Dreyer* [_[link to article](https://academic.oup.com/ijpor/article-abstract/36/4/edae054/7831234)_]

**Abstract:** Decision-makers and commentators are calling Europe’s present political predicament a polycrisis: a period of overlapping, urgent, and mutually reinforcing crises with climate change and Russia’s invasion of Ukraine as key challenges. Our knowledge about how citizens perceive and respond to polycrisis is limited. This paper presents a preregistered survey experiment from Denmark with 4,017 nationally representative respondents. We study crisis perceptions and willingness to act for the climate and Ukraine after concurrently priming both issues. Overall, threat perceptions increase but so does inaction. Climate change drives increases in threat perception and worry, while the war in Ukraine drives a reduction in willingness to act and pay. The results challenge the ‘finite pool of worry’ hypothesis, which presupposes that worry about new, urgent threats will crowd out worry about existing problems, especially in case of climate change. Rather willingness to act under polycrisis is issue-specific and shaped by concrete pocketbook costs, as our experimental evidence illustrates. The results also have important policy implications at a time when decision-makers frequently justify political action through polycrisis discourse.

#### __4. When the election rains out and how bad weather excludes marginal voters from turning out__

*Published in Electoral Studies (2023), co-authored with Kasper M. Hansen* [_[link to open access article](https://sciencedirect.com/science/article/pii/S0261379422001299)_]

**Abstract:** Ostensibly random and trivial experiences of everyday life, e.g., local weather, can have significant political consequences. First, we present a comprehensive meta-analysis of 34 studies of electoral turnout and rainfall – the vast majority demonstrating a negative association. Secondly, we present a new analysis of a voter panel with validated turnout for a complete electorate merged with fine-grained meteorological observations to show that Election Day rainfall reduces turnout by 0.95 percentage points per centimeter, while more sunshine increases turnout. Marginal voters (young voters) are up to six times more susceptible to bad weather and respond more positively to pleasant weather. Thus, bad weather exacerbates unequal democratic participation by pushing low-propensity voters to abstain. Efforts to include marginal voters therefore ought to be intensified during poor weather, and elections could even be moved to seasons with more pleasant weather to improve participatory equality.

#### __5. Mass media influence on the rapid rise of climate change__

*Published in International Journal of Public Opinion Research (2022)* [_[link to article](https://doi.org/10.1080/01402382.2020.1792731)_]

**Abstract:** When a political issue rises to the top of the public agenda, it puts pressure on decisionmakers, shifts power to actors engaging with the issue, and opens a window of opportunity. This article shows that online mass media contributed to the rapid rise of climate change on European public agendas in and around 2019. It also suggests that issue publics, i.e., particularly concerned and interested citizens, were influenced most. Conversely, citizens without strong climate opinions are not subject to influence from intensive media coverage. The results come from vector autoregression (VAR) models that take advantage of unique daily salience time series. The time series are constructed from weekly repeated nationally representative surveys of the public (N=25,445) and online news articles (N=6,905) by a dominant mass media news outlet that boasts a particularly large, trustful, and diverse audience. Traditional mass media can retain a powerful agenda-setting role even in increasingly fragmented media environments. But the target of their influence depends on the issue and the composition of corresponding issue publics, plausibly due in part to individual differences in use and processing of information about the issue.

#### __6. How weather experiences strengthen climate opinions in Europe__

*Published in West European Politics (2021)* [_[link to article](https://doi.org/10.1093/ijpor/edac009)_]

**Abstract:** Previous research has shown that we believe more in the reality of climate change when we experience warmer-than-usual temperatures. This reflects a psychological process in which easily accessible information from personal weather experiences is used as a heuristic to form climate opinions. This paper replicates and extends upon a research design and results of Egan and Mullin to provide the first systematic European study of the Local Warming Effect. Based on data from 12 European countries, the analysis shows that when objective temperatures increase by two standard deviations (5°C) relative to normal temperatures, climate opinions are strengthened by around 0.5–1.0 percentage points – comparable to the effect of a full step to the left on a 0–10 political ideology scale.

## Book chapters

#### __1. Næsten fuld plade på politiske emner: Socialdemokratiet får medvind fra emneejerskab over klima og sundhed__

*Co-authored with Henrik B. Seeberg (2024). In K.M. Hansen & R. Stubager, Partiledernes kamp om midten: Folketingsvalget 2022* [_[link to book](https://djoefforlag.dk/products/partiledernes-kamp-om-midten)_]

#### __2. Klima er vigtigt for vælgerne, især i fremtiden__ 

*Co-authored with Johannes Andersen (2024). In K.M. Hansen & R. Stubager, Partiledernes kamp om midten: Folketingsvalget 2022* [_[link to book](https://djoefforlag.dk/products/partiledernes-kamp-om-midten)_]

## Working papers

#### __1. Raising awareness of harassment against politicians: Experimental evidence on the democratic consequences from four European democracies__

*Co-authored with Karina Kosiara-Pedersen*

#### __2. Snowflakes or Tough Cookies? How Europeans judge harassment against politicians__

*Co-authored with Karina Kosiara-Pedersen*

#### __3. “Young and Naïve”: Sexism and Ageism shape Harassment against Young Candidates and Representatives__

*Co-authored with Karina Kosiara-Pedersen & Christina Fiig.*